In [ ]:
import numpy as np
import pandas as pd
dataset1 = pd.read_csv("20160930_203718.csv")

: 

In [271]:
dataset1.head() #first 5 column

Time (s)  CO (ppm)  Humidity (%r.h.)  Temperature (C)  Flow rate (mL/min)  \
0     0.000       0.0           49.7534          23.7184            233.2737   
1     0.309       0.0           55.8400          26.6200            241.6323   
2     0.618       0.0           55.8400          26.6200            241.3888   
3     0.926       0.0           55.8400          26.6200            241.1461   
4     1.234       0.0           55.8400          26.6200            240.9121   

   Heater voltage (V)  R1 (MOhm)  R2 (MOhm)  R3 (MOhm)  R4 (MOhm)  R5 (MOhm)  \
0              0.8993     0.2231     0.6365     1.1493     0.8483     1.2534   
1              0.2112     2.1314     5.3552     9.7569     6.3188     9.4472   
2              0.2070    10.5318    22.5612    37.2635    17.7848    33.0704   
3              0.2042    29.5749    49.5111    65.6318    26.1447    58.3847   
4              0.2030    49.5111    67.0368    77.8317    27.9625    71.7732   

   R6 (MOhm)  R7 (MOhm)  R8 (MOhm)  R9 (MOhm)  R10 (MOhm)  R11 (MOhm)  \
0     1.4449     1.9906     1.3303     1.4480      1.9148      3.4651   
1    10.5769    13.6317    21.9829    16.1902     24.2780     31.1014   
2    36.3160    42.5746    49.7495    31.7533     57.7289     53.6275   
3    67.5130    68.0064    59.2824    36.7821     66.0832     66.8349   
4    79.9474    79.8631    62.5385    39.6271     68.1441     62.0947   

   R12 (MOhm)  R13 (MOhm)  R14 (MOhm)  
0      5.2144      6.5806      8.6385  
1     34.7193     31.7505     41.9167  
2     56.9212     47.8255     62.9436  
3     66.9695     50.3730     64.8363  
4     49.4614     52.8453     66.8445

In [272]:
dataset1.tail()#last 5 columns

Time (s)  CO (ppm)  Humidity (%r.h.)  Temperature (C)  \
295714  90908.545       0.0              62.3            26.58   
295715  90908.853       0.0              62.3            26.58   
295716  90909.162       0.0              62.3            26.58   
295717  90909.469       0.0              62.3            26.58   
295718  90909.778       0.0              62.3            26.58   

        Flow rate (mL/min)  Heater voltage (V)  R1 (MOhm)  R2 (MOhm)  \
295714                 0.0                 0.2     5.5429     2.5713   
295715                 0.0                 0.2     4.5527     2.1454   
295716                 0.0                 0.2     3.7374     1.8492   
295717                 0.0                 0.2     3.1197     1.6190   
295718                 0.0                 0.2     2.6417     1.4409   

        R3 (MOhm)  R4 (MOhm)  R5 (MOhm)  R6 (MOhm)  R7 (MOhm)  R8 (MOhm)  \
295714    10.3815    18.5796    36.4589    34.4549    38.3745    57.5888   
295715     8.5494    18.0592    36.6290    34.0052    37.6964    51.9752   
295716     7.1062    18.0087    36.0127    32.5056    37.1882    54.4724   
295717     5.9138    17.6950    37.5930    30.5253    35.9328    51.9752   
295718     4.9396    17.0448    35.1252    29.4024    35.2025    58.0412   

        R9 (MOhm)  R10 (MOhm)  R11 (MOhm)  R12 (MOhm)  R13 (MOhm)  R14 (MOhm)  
295714    45.7953     56.6351     56.4058     50.6129     43.0232     65.2822  
295715    45.0239     58.9374     61.6173     50.9361     43.4604     63.8761  
295716    45.0239     59.7462     57.1452     51.8182     42.5944     64.3090  
295717    45.5201     57.7289     60.3791     50.3466     42.4022     62.0375  
295718    43.1405     58.1498     56.0760     51.5393     41.9854     47.5339

In [273]:
dataset1.isnull().sum()

Time (s)              0
CO (ppm)              0
Humidity (%r.h.)      0
Temperature (C)       0
Flow rate (mL/min)    0
Heater voltage (V)    0
R1 (MOhm)             0
R2 (MOhm)             0
R3 (MOhm)             0
R4 (MOhm)             0
R5 (MOhm)             0
R6 (MOhm)             0
R7 (MOhm)             0
R8 (MOhm)             0
R9 (MOhm)             0
R10 (MOhm)            0
R11 (MOhm)            0
R12 (MOhm)            0
R13 (MOhm)            0
R14 (MOhm)            0
dtype: int64

In [274]:
#as there is no null value so no need to drop columns
#df=dataset1.drop(['GENDER','PARTNER','MOTHER_EDU','FATHER_EDU','#_SIBLINGS','KIDS','AGE','HS_TYPE'],axis=1)

In [275]:
df=dataset1
df.shape

(295719, 20)

In [276]:
df.dtypes

Time (s)              float64
CO (ppm)              float64
Humidity (%r.h.)      float64
Temperature (C)       float64
Flow rate (mL/min)    float64
Heater voltage (V)    float64
R1 (MOhm)             float64
R2 (MOhm)             float64
R3 (MOhm)             float64
R4 (MOhm)             float64
R5 (MOhm)             float64
R6 (MOhm)             float64
R7 (MOhm)             float64
R8 (MOhm)             float64
R9 (MOhm)             float64
R10 (MOhm)            float64
R11 (MOhm)            float64
R12 (MOhm)            float64
R13 (MOhm)            float64
R14 (MOhm)            float64
dtype: object

In [277]:
df.isna().sum()

Time (s)              0
CO (ppm)              0
Humidity (%r.h.)      0
Temperature (C)       0
Flow rate (mL/min)    0
Heater voltage (V)    0
R1 (MOhm)             0
R2 (MOhm)             0
R3 (MOhm)             0
R4 (MOhm)             0
R5 (MOhm)             0
R6 (MOhm)             0
R7 (MOhm)             0
R8 (MOhm)             0
R9 (MOhm)             0
R10 (MOhm)            0
R11 (MOhm)            0
R12 (MOhm)            0
R13 (MOhm)            0
R14 (MOhm)            0
dtype: int64

In [278]:
df.isna().sum().sum()

0

In [279]:
df

Time (s)  CO (ppm)  Humidity (%r.h.)  Temperature (C)  \
0           0.000       0.0           49.7534          23.7184   
1           0.309       0.0           55.8400          26.6200   
2           0.618       0.0           55.8400          26.6200   
3           0.926       0.0           55.8400          26.6200   
4           1.234       0.0           55.8400          26.6200   
...           ...       ...               ...              ...   
295714  90908.545       0.0           62.3000          26.5800   
295715  90908.853       0.0           62.3000          26.5800   
295716  90909.162       0.0           62.3000          26.5800   
295717  90909.469       0.0           62.3000          26.5800   
295718  90909.778       0.0           62.3000          26.5800   

        Flow rate (mL/min)  Heater voltage (V)  R1 (MOhm)  R2 (MOhm)  \
0                 233.2737              0.8993     0.2231     0.6365   
1                 241.6323              0.2112     2.1314     5.3552   
2                 241.3888              0.2070    10.5318    22.5612   
3                 241.1461              0.2042    29.5749    49.5111   
4                 240.9121              0.2030    49.5111    67.0368   
...                    ...                 ...        ...        ...   
295714              0.0000              0.2000     5.5429     2.5713   
295715              0.0000              0.2000     4.5527     2.1454   
295716              0.0000              0.2000     3.7374     1.8492   
295717              0.0000              0.2000     3.1197     1.6190   
295718              0.0000              0.2000     2.6417     1.4409   

        R3 (MOhm)  R4 (MOhm)  R5 (MOhm)  R6 (MOhm)  R7 (MOhm)  R8 (MOhm)  \
0          1.1493     0.8483     1.2534     1.4449     1.9906     1.3303   
1          9.7569     6.3188     9.4472    10.5769    13.6317    21.9829   
2         37.2635    17.7848    33.0704    36.3160    42.5746    49.7495   
3         65.6318    26.1447    58.3847    67.5130    68.0064    59.2824   
4         77.8317    27.9625    71.7732    79.9474    79.8631    62.5385   
...           ...        ...        ...        ...        ...        ...   
295714    10.3815    18.5796    36.4589    34.4549    38.3745    57.5888   
295715     8.5494    18.0592    36.6290    34.0052    37.6964    51.9752   
295716     7.1062    18.0087    36.0127    32.5056    37.1882    54.4724   
295717     5.9138    17.6950    37.5930    30.5253    35.9328    51.9752   
295718     4.9396    17.0448    35.1252    29.4024    35.2025    58.0412   

        R9 (MOhm)  R10 (MOhm)  R11 (MOhm)  R12 (MOhm)  R13 (MOhm)  R14 (MOhm)  
0          1.4480      1.9148      3.4651      5.2144      6.5806      8.6385  
1         16.1902     24.2780     31.1014     34.7193     31.7505     41.9167  
2         31.7533     57.7289     53.6275     56.9212     47.8255     62.9436  
3         36.7821     66.0832     66.8349     66.9695     50.3730     64.8363  
4         39.6271     68.1441     62.0947     49.4614     52.8453     66.8445  
...           ...         ...         ...         ...         ...         ...  
295714    45.7953     56.6351     56.4058     50.6129     43.0232     65.2822  
295715    45.0239     58.9374     61.6173     50.9361     43.4604     63.8761  
295716    45.0239     59.7462     57.1452     51.8182     42.5944     64.3090  
295717    45.5201     57.7289     60.3791     50.3466     42.4022     62.0375  
295718    43.1405     58.1498     56.0760     51.5393     41.9854     47.5339  

[295719 rows x 20 columns]

In [280]:
df.isna().sum().sum()

0

In [281]:
from sklearn.preprocessing import LabelEncoder 
le= LabelEncoder() 
label_encoder_x= LabelEncoder()  
df.iloc[:, 0] = le.fit_transform(df.iloc[:, 0])

C:\Users\ak_vishwakarma_0\AppData\Local\Temp\ipykernel_11804\2669919472.py:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:, 0] = le.fit_transform(df.iloc[:, 0])


In [282]:
df

Time (s)  CO (ppm)  Humidity (%r.h.)  Temperature (C)  \
0              0       0.0           49.7534          23.7184   
1              1       0.0           55.8400          26.6200   
2              2       0.0           55.8400          26.6200   
3              3       0.0           55.8400          26.6200   
4              4       0.0           55.8400          26.6200   
...          ...       ...               ...              ...   
295714    295714       0.0           62.3000          26.5800   
295715    295715       0.0           62.3000          26.5800   
295716    295716       0.0           62.3000          26.5800   
295717    295717       0.0           62.3000          26.5800   
295718    295718       0.0           62.3000          26.5800   

        Flow rate (mL/min)  Heater voltage (V)  R1 (MOhm)  R2 (MOhm)  \
0                 233.2737              0.8993     0.2231     0.6365   
1                 241.6323              0.2112     2.1314     5.3552   
2                 241.3888              0.2070    10.5318    22.5612   
3                 241.1461              0.2042    29.5749    49.5111   
4                 240.9121              0.2030    49.5111    67.0368   
...                    ...                 ...        ...        ...   
295714              0.0000              0.2000     5.5429     2.5713   
295715              0.0000              0.2000     4.5527     2.1454   
295716              0.0000              0.2000     3.7374     1.8492   
295717              0.0000              0.2000     3.1197     1.6190   
295718              0.0000              0.2000     2.6417     1.4409   

        R3 (MOhm)  R4 (MOhm)  R5 (MOhm)  R6 (MOhm)  R7 (MOhm)  R8 (MOhm)  \
0          1.1493     0.8483     1.2534     1.4449     1.9906     1.3303   
1          9.7569     6.3188     9.4472    10.5769    13.6317    21.9829   
2         37.2635    17.7848    33.0704    36.3160    42.5746    49.7495   
3         65.6318    26.1447    58.3847    67.5130    68.0064    59.2824   
4         77.8317    27.9625    71.7732    79.9474    79.8631    62.5385   
...           ...        ...        ...        ...        ...        ...   
295714    10.3815    18.5796    36.4589    34.4549    38.3745    57.5888   
295715     8.5494    18.0592    36.6290    34.0052    37.6964    51.9752   
295716     7.1062    18.0087    36.0127    32.5056    37.1882    54.4724   
295717     5.9138    17.6950    37.5930    30.5253    35.9328    51.9752   
295718     4.9396    17.0448    35.1252    29.4024    35.2025    58.0412   

        R9 (MOhm)  R10 (MOhm)  R11 (MOhm)  R12 (MOhm)  R13 (MOhm)  R14 (MOhm)  
0          1.4480      1.9148      3.4651      5.2144      6.5806      8.6385  
1         16.1902     24.2780     31.1014     34.7193     31.7505     41.9167  
2         31.7533     57.7289     53.6275     56.9212     47.8255     62.9436  
3         36.7821     66.0832     66.8349     66.9695     50.3730     64.8363  
4         39.6271     68.1441     62.0947     49.4614     52.8453     66.8445  
...           ...         ...         ...         ...         ...         ...  
295714    45.7953     56.6351     56.4058     50.6129     43.0232     65.2822  
295715    45.0239     58.9374     61.6173     50.9361     43.4604     63.8761  
295716    45.0239     59.7462     57.1452     51.8182     42.5944     64.3090  
295717    45.5201     57.7289     60.3791     50.3466     42.4022     62.0375  
295718    43.1405     58.1498     56.0760     51.5393     41.9854     47.5339  

[295719 rows x 20 columns]

# label encoder is used to get sutdent id values in categorical data

In [283]:
j=1
for i in range (0,144):
  df.at[i,'STUDENTID']=i
  j=j+1


### above function is used to change column = STUDENTID values

In [284]:
df.head()

Time (s)  CO (ppm)  Humidity (%r.h.)  Temperature (C)  Flow rate (mL/min)  \
0         0       0.0           49.7534          23.7184            233.2737   
1         1       0.0           55.8400          26.6200            241.6323   
2         2       0.0           55.8400          26.6200            241.3888   
3         3       0.0           55.8400          26.6200            241.1461   
4         4       0.0           55.8400          26.6200            240.9121   

   Heater voltage (V)  R1 (MOhm)  R2 (MOhm)  R3 (MOhm)  R4 (MOhm)  ...  \
0              0.8993     0.2231     0.6365     1.1493     0.8483  ...   
1              0.2112     2.1314     5.3552     9.7569     6.3188  ...   
2              0.2070    10.5318    22.5612    37.2635    17.7848  ...   
3              0.2042    29.5749    49.5111    65.6318    26.1447  ...   
4              0.2030    49.5111    67.0368    77.8317    27.9625  ...   

   R6 (MOhm)  R7 (MOhm)  R8 (MOhm)  R9 (MOhm)  R10 (MOhm)  R11 (MOhm)  \
0     1.4449     1.9906     1.3303     1.4480      1.9148      3.4651   
1    10.5769    13.6317    21.9829    16.1902     24.2780     31.1014   
2    36.3160    42.5746    49.7495    31.7533     57.7289     53.6275   
3    67.5130    68.0064    59.2824    36.7821     66.0832     66.8349   
4    79.9474    79.8631    62.5385    39.6271     68.1441     62.0947   

   R12 (MOhm)  R13 (MOhm)  R14 (MOhm)  STUDENTID  
0      5.2144      6.5806      8.6385        0.0  
1     34.7193     31.7505     41.9167        1.0  
2     56.9212     47.8255     62.9436        2.0  
3     66.9695     50.3730     64.8363        3.0  
4     49.4614     52.8453     66.8445        4.0  

[5 rows x 21 columns]

In [285]:
df.info() #count and datatype of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295719 entries, 0 to 295718
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Time (s)            295719 non-null  int64  
 1   CO (ppm)            295719 non-null  float64
 2   Humidity (%r.h.)    295719 non-null  float64
 3   Temperature (C)     295719 non-null  float64
 4   Flow rate (mL/min)  295719 non-null  float64
 5   Heater voltage (V)  295719 non-null  float64
 6   R1 (MOhm)           295719 non-null  float64
 7   R2 (MOhm)           295719 non-null  float64
 8   R3 (MOhm)           295719 non-null  float64
 9   R4 (MOhm)           295719 non-null  float64
 10  R5 (MOhm)           295719 non-null  float64
 11  R6 (MOhm)           295719 non-null  float64
 12  R7 (MOhm)           295719 non-null  float64
 13  R8 (MOhm)           295719 non-null  float64
 14  R9 (MOhm)           295719 non-null  float64
 15  R10 (MOhm)          295719 non-nul

In [286]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='most_frequent')
df_im=si.fit_transform(df)

In [287]:
df_im=pd.DataFrame(df_im)

In [288]:
df_im


0    1        2        3         4       5        6        7   \
0            0.0  0.0  49.7534  23.7184  233.2737  0.8993   0.2231   0.6365   
1            1.0  0.0  55.8400  26.6200  241.6323  0.2112   2.1314   5.3552   
2            2.0  0.0  55.8400  26.6200  241.3888  0.2070  10.5318  22.5612   
3            3.0  0.0  55.8400  26.6200  241.1461  0.2042  29.5749  49.5111   
4            4.0  0.0  55.8400  26.6200  240.9121  0.2030  49.5111  67.0368   
...          ...  ...      ...      ...       ...     ...      ...      ...   
295714  295714.0  0.0  62.3000  26.5800    0.0000  0.2000   5.5429   2.5713   
295715  295715.0  0.0  62.3000  26.5800    0.0000  0.2000   4.5527   2.1454   
295716  295716.0  0.0  62.3000  26.5800    0.0000  0.2000   3.7374   1.8492   
295717  295717.0  0.0  62.3000  26.5800    0.0000  0.2000   3.1197   1.6190   
295718  295718.0  0.0  62.3000  26.5800    0.0000  0.2000   2.6417   1.4409   

             8        9   ...       11       12       13       14       15  \
0        1.1493   0.8483  ...   1.4449   1.9906   1.3303   1.4480   1.9148   
1        9.7569   6.3188  ...  10.5769  13.6317  21.9829  16.1902  24.2780   
2       37.2635  17.7848  ...  36.3160  42.5746  49.7495  31.7533  57.7289   
3       65.6318  26.1447  ...  67.5130  68.0064  59.2824  36.7821  66.0832   
4       77.8317  27.9625  ...  79.9474  79.8631  62.5385  39.6271  68.1441   
...         ...      ...  ...      ...      ...      ...      ...      ...   
295714  10.3815  18.5796  ...  34.4549  38.3745  57.5888  45.7953  56.6351   
295715   8.5494  18.0592  ...  34.0052  37.6964  51.9752  45.0239  58.9374   
295716   7.1062  18.0087  ...  32.5056  37.1882  54.4724  45.0239  59.7462   
295717   5.9138  17.6950  ...  30.5253  35.9328  51.9752  45.5201  57.7289   
295718   4.9396  17.0448  ...  29.4024  35.2025  58.0412  43.1405  58.1498   

             16       17       18       19   20  
0        3.4651   5.2144   6.5806   8.6385  0.0  
1       31.1014  34.7193  31.7505  41.9167  1.0  
2       53.6275  56.9212  47.8255  62.9436  2.0  
3       66.8349  66.9695  50.3730  64.8363  3.0  
4       62.0947  49.4614  52.8453  66.8445  4.0  
...         ...      ...      ...      ...  ...  
295714  56.4058  50.6129  43.0232  65.2822  0.0  
295715  61.6173  50.9361  43.4604  63.8761  0.0  
295716  57.1452  51.8182  42.5944  64.3090  0.0  
295717  60.3791  50.3466  42.4022  62.0375  0.0  
295718  56.0760  51.5393  41.9854  47.5339  0.0  

[295719 rows x 21 columns]

In [289]:
data=df_im

In [290]:
print(df_im.columns.values)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [291]:
target=df_im[20]

In [292]:
target

0         0.0
1         1.0
2         2.0
3         3.0
4         4.0
         ... 
295714    0.0
295715    0.0
295716    0.0
295717    0.0
295718    0.0
Name: 20, Length: 295719, dtype: float64

In [293]:
target.isna().sum()

0

In [294]:
#df=df.dropna(inplace=True)

In [295]:
#target=target.dropna(inplace=True)

In [296]:
df=df_im

In [297]:
import matplotlib.pyplot as plt
from sklearn import linear_model

In [298]:
from sklearn.model_selection import train_test_split


In [299]:
x_train,x_test,y_train,y_test=train_test_split(df,target,test_size=0.3)

In [300]:
x_train.shape

(207003, 21)

In [301]:
x_test.shape

(88716, 21)

In [302]:
y_train.shape

(207003,)

In [303]:
y_test.shape

(88716,)

In [304]:
from sklearn.linear_model import Perceptron

In [305]:
p1=Perceptron(penalty='l1')

In [306]:
df

0    1        2        3         4       5        6        7   \
0            0.0  0.0  49.7534  23.7184  233.2737  0.8993   0.2231   0.6365   
1            1.0  0.0  55.8400  26.6200  241.6323  0.2112   2.1314   5.3552   
2            2.0  0.0  55.8400  26.6200  241.3888  0.2070  10.5318  22.5612   
3            3.0  0.0  55.8400  26.6200  241.1461  0.2042  29.5749  49.5111   
4            4.0  0.0  55.8400  26.6200  240.9121  0.2030  49.5111  67.0368   
...          ...  ...      ...      ...       ...     ...      ...      ...   
295714  295714.0  0.0  62.3000  26.5800    0.0000  0.2000   5.5429   2.5713   
295715  295715.0  0.0  62.3000  26.5800    0.0000  0.2000   4.5527   2.1454   
295716  295716.0  0.0  62.3000  26.5800    0.0000  0.2000   3.7374   1.8492   
295717  295717.0  0.0  62.3000  26.5800    0.0000  0.2000   3.1197   1.6190   
295718  295718.0  0.0  62.3000  26.5800    0.0000  0.2000   2.6417   1.4409   

             8        9   ...       11       12       13       14       15  \
0        1.1493   0.8483  ...   1.4449   1.9906   1.3303   1.4480   1.9148   
1        9.7569   6.3188  ...  10.5769  13.6317  21.9829  16.1902  24.2780   
2       37.2635  17.7848  ...  36.3160  42.5746  49.7495  31.7533  57.7289   
3       65.6318  26.1447  ...  67.5130  68.0064  59.2824  36.7821  66.0832   
4       77.8317  27.9625  ...  79.9474  79.8631  62.5385  39.6271  68.1441   
...         ...      ...  ...      ...      ...      ...      ...      ...   
295714  10.3815  18.5796  ...  34.4549  38.3745  57.5888  45.7953  56.6351   
295715   8.5494  18.0592  ...  34.0052  37.6964  51.9752  45.0239  58.9374   
295716   7.1062  18.0087  ...  32.5056  37.1882  54.4724  45.0239  59.7462   
295717   5.9138  17.6950  ...  30.5253  35.9328  51.9752  45.5201  57.7289   
295718   4.9396  17.0448  ...  29.4024  35.2025  58.0412  43.1405  58.1498   

             16       17       18       19   20  
0        3.4651   5.2144   6.5806   8.6385  0.0  
1       31.1014  34.7193  31.7505  41.9167  1.0  
2       53.6275  56.9212  47.8255  62.9436  2.0  
3       66.8349  66.9695  50.3730  64.8363  3.0  
4       62.0947  49.4614  52.8453  66.8445  4.0  
...         ...      ...      ...      ...  ...  
295714  56.4058  50.6129  43.0232  65.2822  0.0  
295715  61.6173  50.9361  43.4604  63.8761  0.0  
295716  57.1452  51.8182  42.5944  64.3090  0.0  
295717  60.3791  50.3466  42.4022  62.0375  0.0  
295718  56.0760  51.5393  41.9854  47.5339  0.0  

[295719 rows x 21 columns]

In [307]:
#df=df.drop(145, axis=0)

In [308]:
df


0    1        2        3         4       5        6        7   \
0            0.0  0.0  49.7534  23.7184  233.2737  0.8993   0.2231   0.6365   
1            1.0  0.0  55.8400  26.6200  241.6323  0.2112   2.1314   5.3552   
2            2.0  0.0  55.8400  26.6200  241.3888  0.2070  10.5318  22.5612   
3            3.0  0.0  55.8400  26.6200  241.1461  0.2042  29.5749  49.5111   
4            4.0  0.0  55.8400  26.6200  240.9121  0.2030  49.5111  67.0368   
...          ...  ...      ...      ...       ...     ...      ...      ...   
295714  295714.0  0.0  62.3000  26.5800    0.0000  0.2000   5.5429   2.5713   
295715  295715.0  0.0  62.3000  26.5800    0.0000  0.2000   4.5527   2.1454   
295716  295716.0  0.0  62.3000  26.5800    0.0000  0.2000   3.7374   1.8492   
295717  295717.0  0.0  62.3000  26.5800    0.0000  0.2000   3.1197   1.6190   
295718  295718.0  0.0  62.3000  26.5800    0.0000  0.2000   2.6417   1.4409   

             8        9   ...       11       12       13       14       15  \
0        1.1493   0.8483  ...   1.4449   1.9906   1.3303   1.4480   1.9148   
1        9.7569   6.3188  ...  10.5769  13.6317  21.9829  16.1902  24.2780   
2       37.2635  17.7848  ...  36.3160  42.5746  49.7495  31.7533  57.7289   
3       65.6318  26.1447  ...  67.5130  68.0064  59.2824  36.7821  66.0832   
4       77.8317  27.9625  ...  79.9474  79.8631  62.5385  39.6271  68.1441   
...         ...      ...  ...      ...      ...      ...      ...      ...   
295714  10.3815  18.5796  ...  34.4549  38.3745  57.5888  45.7953  56.6351   
295715   8.5494  18.0592  ...  34.0052  37.6964  51.9752  45.0239  58.9374   
295716   7.1062  18.0087  ...  32.5056  37.1882  54.4724  45.0239  59.7462   
295717   5.9138  17.6950  ...  30.5253  35.9328  51.9752  45.5201  57.7289   
295718   4.9396  17.0448  ...  29.4024  35.2025  58.0412  43.1405  58.1498   

             16       17       18       19   20  
0        3.4651   5.2144   6.5806   8.6385  0.0  
1       31.1014  34.7193  31.7505  41.9167  1.0  
2       53.6275  56.9212  47.8255  62.9436  2.0  
3       66.8349  66.9695  50.3730  64.8363  3.0  
4       62.0947  49.4614  52.8453  66.8445  4.0  
...         ...      ...      ...      ...  ...  
295714  56.4058  50.6129  43.0232  65.2822  0.0  
295715  61.6173  50.9361  43.4604  63.8761  0.0  
295716  57.1452  51.8182  42.5944  64.3090  0.0  
295717  60.3791  50.3466  42.4022  62.0375  0.0  
295718  56.0760  51.5393  41.9854  47.5339  0.0  

[295719 rows x 21 columns]

In [309]:
p1.fit(x_train,y_train)

c:\Users\ak_vishwakarma_0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


Perceptron(penalty='l1')

In [310]:
from sklearn.metrics import accuracy_score

In [311]:
train_pred=p1.predict(x_train)

In [312]:
train_pred=p1.predict(x_test)

In [316]:
X=df
from sklearn.linear_model import LogisticRegression

from sklearn import preprocessing
from sklearn import utils

#convert y values to categorical values
lab = preprocessing.LabelEncoder()
y = lab.fit_transform(target)


In [317]:

#split the dataset in the Training and testing 
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train, y_test = train_test_split(df,target,test_size=0.2,random_state=0)
print(np.shape(X))
print(np.shape(X_test))
print(np.shape(X_train))

#Create the object of StandardScaler class for independent variables or features
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

(295719, 21)
(59144, 21)
(236575, 21)


In [318]:
### SVM (Support Vector Machine)
from sklearn.svm import SVC
svm = SVC(kernel='linear', C=1,random_state=0)
svm.fit(X_train_std,y_train)
y_pred=svm.predict(X_test_std)
print('misclassified samples: %d'%(y_test!=y_pred).sum())
from sklearn.metrics import accuracy_score
print('Accuracy:%.2f'%accuracy_score(y_test,y_pred))

misclassified samples: 25
Accuracy:1.00


In [319]:
### KNN (K-Nearest Neighbors)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn1=KNeighborsClassifier(n_neighbors=4)
knn1.fit(X_train_std,y_train)
y_pred=knn1.predict(X_test_std)
print('misclassified samples: %d'%(y_test!=y_pred).sum())
from sklearn.metrics import accuracy_score
print('Accuracy:%.2f'%accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)

misclassified samples: 25
Accuracy:1.00
[[59119     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     1     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     1     0     0]]


In [320]:
### Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(X_train,y_train)
model = LogisticRegression(solver='liblinear', random_state=0).fit(X, y)
model.predict_proba(X)
model.predict(X)
model.score(X,y)
print(classification_report(y, model.predict(X)))
model.score(X,y)

c:\Users\ak_vishwakarma_0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ak_vishwakarma_0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ak_vishwakarma_0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control th

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    295576
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         1
           9       1.00      1.00      1.00         1
          10       1.00      1.00      1.00         1
          11       1.00      1.00      1.00         1
          12       1.00      1.00      1.00         1
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       1.00      1.00      1.00         1
          16       1.00      1.00      1.00         1
          17       1.00    

0.9998038678610438